# Generated by Django 3.0.5 on 2020-04-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categorie',
            field=models.CharField(choices=[(1, 'Bursaspor'), (2, 'Bursa')], max_length=25),
        ),
    ]
