# Generated by Django 3.0.5 on 2020-04-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200411_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='home',
            field=models.CharField(choices=[('1', 'Anasayfada Goster'), ('2', 'Anasayfada Gosterme')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='categorie',
            field=models.CharField(choices=[('1', 'Bursaspor'), ('2', 'Bursa')], max_length=25),
        ),
    ]
