# Generated by Django 3.0.5 on 2020-04-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200411_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('1', 'Bursaspor'), ('2', 'Bursa')], max_length=25)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
