# Generated by Django 3.0.5 on 2020-04-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Tarih'),
        ),
    ]
